// Script de seed — pré-cadastra diretores, autoridades e convidados
// Todos entram com status 'pendente' (recepção confirma presença no dia)
//
// Uso:
//   node seed.js          → insere apenas quem ainda não está no banco
//   node seed.js --limpar → apaga tudo e reinicia (CUIDADO)

// Importa o database.js que já cria as tabelas e aplica as migrações
const db = require('./database');

const PESSOAS = [

  // ── CONVIDADOS / HERÓIS DA SAÚDE ────────────────────────────────
  {
    nome: 'Daiane Regis Pereira',
    cargo: 'Técnica de Enfermagem',
    local_trabalho: 'CLINICA E NEFROLOGIA LESTE',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Douglas do Nascimento Pocinho –',
    cargo: 'Técnico de Enfermagem',
    local_trabalho: 'HOSP ALVARENGA',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'IVETE TERESA DE SOUZA ALVARENGA',
    cargo: 'Técnica de Enfermagem.',
    local_trabalho: 'HOSP DO RIM - FUNDAÇÃO OSWALDO RAMOS',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'JULIANO GUEDES GALDINO',
    local_trabalho: 'IMED',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Maria Dorotéia Guglielmi',
    cargo: 'Enfermeira',
    local_trabalho: 'SANTA CASA DE SÃO PAULO',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Nelson de Souza Assunção',
    local_trabalho: 'Colsan',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Nilda Rosa Prado',
    cargo: 'gerente de enfermagem',
    local_trabalho: 'Sírio-Libanês',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Silmaia Tavares Santos',
    cargo: 'TEC.ENF. TRABALHO SR',
    local_trabalho: 'CEJAM',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Uberlândia dos Santos Nascimento',
    local_trabalho: 'Hospital Municipal de Guarapiranga',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Domenico Antonio Donina Rodrigues',
    cargo: 'Dentista',
    local_trabalho: 'Ubs vila Isolina Mazzei',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Larissa Pinheiro Fioratti',
    cargo: 'Nutricionista',
    local_trabalho: 'Universidade Paulista - UNIP',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'JOSÉ MESSIAS DOS SANTOS',
    cargo: 'TÉCNICO DE ENFERMAGEM',
    local_trabalho: 'Prefeitura Municipal de São Caetano do Sul',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'claudio santos albuquerque',
    cargo: 'imprensa',
    local_trabalho: 'Cidadao Consciente',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Maria de Lourdes Pereira Lima',
    cargo: 'TEC de enfermagem',
    local_trabalho: 'Associação saúde da família',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Sidney Gomes martins',
    cargo: 'Técnico de enfermagem',
    local_trabalho: 'Hospital Albert Einstein',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Osvaldo de lima Júnior',
    cargo: 'Técnico de enfermagem',
    local_trabalho: 'Prefeitura municipal de Diadema',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Eduarda Bezerra Martins',
    cargo: 'Técnica de Enfermagem',
    local_trabalho: 'Hospital Regional do Alto Tietê',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Jessica Aparecida Lopes Barduchi',
    cargo: 'Técnica de enfermagem',
    local_trabalho: 'Caps Ad 2 VILA MADALENA PROSAM',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Eliana Pinto Dos Santos',
    cargo: 'Auxiliar de enfermagem',
    local_trabalho: 'Spdm-pais',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'MIRIAN COSTA',
    cargo: 'AADVOGADA , JORNALISTA , ATIVISTA SOCIAL',
    local_trabalho: 'INCVF E FORENSE TEAM VRASIL/USA',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Douglas Rafael Bueno Bernardes',
    cargo: 'Tenente Enfermeiro',
    local_trabalho: 'Força Aérea / Comando da Aeronáutica',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Denis Mendes da Silva Rios',
    cargo: 'Enfermeiro',
    local_trabalho: '11Care',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Ana Célia Edvirges de Sousa',
    cargo: 'Técnico de enfermagem',
    local_trabalho: 'Spdmpais Hospital Municipal do Tatuapé - Dr. Cármino Caricchio',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Gabriel Henrique Rodrigues Leonardo',
    cargo: 'Coordenador médico',
    local_trabalho: 'Seconci',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Agatha Mesaroch',
    cargo: 'Enfermeira',
    local_trabalho: 'FUABC - Prefeitura Municipal de São Caetano do Sul',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Fabiana de Azevedo Garcia dos Santos',
    cargo: 'Técnica de enfermagem',
    local_trabalho: 'Sociedade Beneficente Caminho de Damasco',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Vanessa damazio dos Santos Pereira',
    cargo: 'Técnica de enfermagem',
    local_trabalho: 'Hospital Pitangueiras',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Lucas Marinho Goes de Sousa',
    cargo: 'Enfermeiro',
    local_trabalho: 'Casa de saúde Santa Marcelina',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'HILDA OLIVEIRA BARRETO',
    cargo: 'Enfermeira',
    local_trabalho: 'INTS/ UPA Pedreira',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Elizângela Pereira Guedes',
    cargo: 'Enfermeira da Padronização de Materiais',
    local_trabalho: 'Santa Casa de Misericórdia de São Paulo',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Elane de Fátima de Lima Santos',
    cargo: 'Auxiliar de enfermagem',
    local_trabalho: 'Hospital geral do pedreira',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Neuza Aparecida Ferreira dos Santos',
    cargo: 'Aposentada',
    local_trabalho: 'Aposentada',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Erisvaldo Rodrigues da Silva',
    cargo: 'Tecnico de Enfermagem',
    local_trabalho: 'Prefeitura Municipal de Santos',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'ELLEN KARINA DOS SANTOS',
    cargo: 'COORDENADOR DE ENFERMAGEM',
    local_trabalho: 'FUNDAÇÃO ABC /HOSPITAL GUILHERME ÁLVARO',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Thais Barbosa do Nascimento',
    cargo: 'Técnico de farmácia',
    local_trabalho: 'Santa marcelina/ UBS Jardim Vitória',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Amanda Mendes de Maria Fernandes',
    cargo: 'Auxiliar de enfermagem',
    local_trabalho: 'Santa Marcelina',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Caio da Silva Gonçalves',
    cargo: 'Gerente técnico',
    local_trabalho: 'UBS CATERINA DALLANESE',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Angela Ribeiro Lopes de Almeida',
    cargo: 'Auxiliar de enfermagem',
    local_trabalho: 'Hospital Alvarenga',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Tatiane Protasio de Oliveira',
    cargo: 'Auxiliar de enfermagem',
    local_trabalho: 'Spdm',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Priscila Alves da Silva',
    cargo: 'Curativista/ Tec. De saúde bucal/ Diretoria da Associação Mulheres em Ação',
    local_trabalho: 'Cuidadora de idosos autônoma/particular e na Associação Mulheres em Ação da Vila Queiroz em prol da comunidade e voluntária.',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Simone Aparecida de Moura Notaro',
    cargo: 'Auxiliar de Enfermagem',
    local_trabalho: 'Hospital Ipiranga',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Daniela dos Santos Batista',
    cargo: 'Nutricionista',
    local_trabalho: 'Particular',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Maria Aparecida Alves Sousa',
    cargo: 'Tecnico de enfermagem',
    local_trabalho: 'UFES/HUCAM',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Ana Cristina Ribeiro',
    cargo: 'Enfermeira',
    local_trabalho: 'ENESP',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'João Henrique Muniz de Melo',
    cargo: 'Técnico de enfermagem',
    local_trabalho: 'SAMU 192 - Mogi das Cruzes',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Maryane Silva da Fonseca',
    cargo: 'Técnica de enfermagem',
    local_trabalho: 'Sociedade Brasileira caminho de damasco',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Crislaine Lidovina da Silva',
    cargo: 'Enfermeira',
    local_trabalho: 'Hospital das clinicas da faculdade de medicina da usp',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Adriano Roberto da Silva',
    cargo: 'Técnico de enfermagem',
    local_trabalho: 'Nefrostar',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Ligia da Silva Lima',
    cargo: 'Técnica de Enfermagem',
    local_trabalho: 'INTS',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Fernando Ribeiro da Silva',
    cargo: 'Supervisor de Enfermagem',
    local_trabalho: 'Hospital Alvorada Moema',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Fátima Marangon gauna Quirino',
    cargo: 'Aposentada',
    local_trabalho: 'Sindicato',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Naína De Oliveira Coelho',
    cargo: 'Enfermeira',
    local_trabalho: 'UBS Jardim Gabriela',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Maria Lucia Ornelas Chaves Tozato',
    cargo: 'Assistente Social',
    local_trabalho: 'Prefeitura Municipal de São Caetano do Sul',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Polienny Rodrigues da Silva Felix',
    cargo: 'Técnica de enfermagem',
    local_trabalho: 'INTS',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Sônia Aparecida Faustino Macedo',
    cargo: 'Análise clínica  farmacêutica',
    local_trabalho: 'Aposentada',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Liz Andrea Santos Carvalho',
    cargo: 'Gerente Assistencial',
    local_trabalho: 'INTS',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Silvana Aparecida Andrade da Cunha',
    cargo: 'Técnica de enfermagem',
    local_trabalho: 'Hospital japonês Santa Cruz',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Vagner Serafim de Deus',
    cargo: 'Gerente de Saúde',
    local_trabalho: 'SAS /SECONCI  HOSPITAL DIA PENHA HATIRO SHIMOMOTO',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Paulo da Silva Amorim',
    cargo: 'Médico / clínico geral',
    local_trabalho: 'Seconci',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Almir Rodrigues da Gama',
    cargo: 'Técnico de Enfermagem',
    local_trabalho: 'Hospital Santa Casa de Misericórdia de Santo Amaro',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'josé carlos ramos',
    cargo: 'técnico de enfermagem',
    local_trabalho: 'spdm pais',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Fabiana Monteiro de Oliveira Silva',
    cargo: 'Técnico de Enfermagem',
    local_trabalho: 'Instituto Dante Pazzanese de Cardiologia',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Angelica Aparecida dos Santos Lessa',
    cargo: 'Técnica de Enfermagem',
    local_trabalho: 'Sbcd',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Irene pedroso da Silva',
    cargo: 'técnica de enfermagem',
    local_trabalho: 'nefrostar Osasco',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Mônica Pereira da Silva Rocha',
    cargo: 'Técnico de Enfermagem',
    local_trabalho: 'Hospital 9 de Julho',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Julzira dos Santos velasquez',
    cargo: 'Serviços  Gerais',
    local_trabalho: 'Hospital Samaritano',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Rosângela Ferreira de Sousa Carvalho',
    cargo: 'Supervisora Adm',
    local_trabalho: 'Santa Casa de Misericórdia de São Paulo',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Carlos  da Silva  Velasquez',
    cargo: 'Auxiliar de Enfermagem',
    local_trabalho: 'Hospital São Paulo  SPDM',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Maria José da Silva',
    cargo: 'Encarregada administrativa',
    local_trabalho: 'Irmandade de misericórdia Santa Casa de São Paulo',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Eduardo donizete de lima',
    cargo: 'Técnico de enfermagem',
    local_trabalho: 'Alpha',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Roseneide da Silva Xavier',
    cargo: 'Enfermeira',
    local_trabalho: 'UPA Pedreira- INTS  - Instituto Nacional de Tecnologia e Saúde.',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Marilucia Moura Ribeiro Mendes',
    cargo: 'Técnica de enfermagem',
    local_trabalho: 'Hospital Euryclides de Jesus Zerbini',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'THIAGO SOUZA DE JESUS',
    cargo: 'Técnico de enfermagem',
    local_trabalho: 'HOSPITAL VITÓRIA',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Valeska Aparecida Marini',
    cargo: 'Enfermeira RT',
    local_trabalho: 'Fuabc',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Luciano Rodrigues da Silva',
    cargo: 'Auxiliar de Enfermagem',
    local_trabalho: 'Hospital Alvorada Moema',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Iran Muniz de Carvalho',
    cargo: 'Tecnico de enfermagem',
    local_trabalho: 'Hospital pronto socorro portinari.',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Dinis Alves da Silva',
    cargo: 'Técnico de Imobilizações Ortopedicas',
    local_trabalho: 'IRSSL Hospital Geral do Grajaú',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Grislaine Ramos de Oliveira',
    cargo: 'Técnico de enfermagem',
    local_trabalho: 'Fundação do ABC',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Wemerson Soares de Oliveira',
    cargo: 'Agente de saúde',
    local_trabalho: 'Santa casa de Misericórdia de SP',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Luciana barros reis',
    cargo: 'Enfermeira III',
    local_trabalho: 'Hospital 9 de julho',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Letícia Kelen Santos Silva',
    cargo: 'Enfermeiro',
    local_trabalho: 'Hospital 9 de Julho',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Vanessa Cavaco de Jesus',
    cargo: 'Analista de Ouvidoria',
    local_trabalho: 'OSS SBCD Sociedade Brasileira Caminho de Damasco',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Carla de Melo Bossan',
    cargo: 'Auxiliar de Enfermagem',
    local_trabalho: 'Hospital das Clinicas da Faculdade de Medicina de São Paulo',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Thiago Rafael',
    cargo: 'Auxiliar de enfermagem',
    local_trabalho: 'Ssvv são Vicente de Paulo',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Ramon Cavalcante Teixeira',
    cargo: 'Médium',
    local_trabalho: 'Casa de caridade Luz e amor',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Viviane Miranda das Neves',
    cargo: 'Auxiliar de enfermagem',
    local_trabalho: 'Associação saúde da Família - ASF',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Maria Elizete Carlos da Silva Herdina',
    cargo: 'Aux de Enfermagem.',
    local_trabalho: 'Hospital São Luíz (Aposentada)',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Ana Maria de Camargo',
    cargo: 'TEC. Enfermagem',
    local_trabalho: 'Alvorada Moema',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Mariuza da Silva',
    cargo: 'Supervisora gerenciamento de leitos',
    local_trabalho: 'Irmandade Santa Casa de Misericórdia de São Paulo',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Francielli santos da silva',
    cargo: 'Enfermeira',
    local_trabalho: 'Santa casa de São Paulo',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Talita Gabrielle do Vale Teixeira Leite',
    cargo: 'Supervisora de Enfermagem',
    local_trabalho: 'Anteriormente Hospital Alvorada de Moema/ Atual Hospital Santa Helena',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Maylson Cesario do Carmo',
    cargo: 'Enfermeiro ( supervisor das UTIs)',
    local_trabalho: 'Santa Casa de Sp',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Adriana Cruz de Goes',
    cargo: 'Técnica de enfer',
    local_trabalho: 'Hospital Albert Einstein',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Fernando Rogério de Jesus',
    cargo: 'Supervisor de Segurança Patrimonial',
    local_trabalho: 'Santa Casa de Misericórdia de São Paulo',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Áurea Cristina Neves Alves',
    cargo: 'Encarregada de Hotelaria',
    local_trabalho: 'Irmandade Santa Casa de Misericórdia de São Paulo',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Caroline Alves Ferreira',
    cargo: 'Coordenadora de Pesquisa Clinica',
    local_trabalho: 'Thermo Fisher Scientific',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Raul Santos Sodré',
    cargo: 'Enfermeiro',
    local_trabalho: 'Oss Sirio Libanês',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Maryana Pereira de Oliveira',
    cargo: 'Técnica de enfermagem',
    local_trabalho: 'Instituto Dante Pazanezze de Cardiologia',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Jeziel Dantas da Silva',
    cargo: 'TEC de enfermagem',
    local_trabalho: 'Hospital Monumento',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Ana Paula Federicci Dellanegra',
    cargo: 'Gerente de Hotelaria',
    local_trabalho: 'Santa Casa de Misericórdia de São Paulo',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'DIEGO DA SILVA',
    cargo: 'Auxiliar de enfermagem',
    local_trabalho: 'Mosteiro São Geraldo de São Paulo',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Maidel Epifania da Silva',
    cargo: 'Técnica de enfermagem',
    local_trabalho: 'Einstein',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Andreia Aparecida Teixeira da Silva',
    cargo: 'Diretora Financeira',
    local_trabalho: 'Associação dos Servidores do Hospital das Clínicas',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Katia Regina Martins',
    cargo: 'Agente de promoção ambiental',
    local_trabalho: 'Seconci sas',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Luciana Alessandra de Carvalho Abdalla',
    cargo: 'Enfermeira',
    local_trabalho: 'Hospital Alvorada Moema',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'MARCUS VINICIUS DE LIMA OLIVEIRA',
    cargo: 'Conselheiro',
    local_trabalho: 'COREN-SP',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Laila Nasser Sati',
    cargo: 'Diretora Pedagógica',
    local_trabalho: 'Colégio 24 de Março',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Marcilene vieira de oliveira santos',
    cargo: 'Técnico de enfermagem',
    local_trabalho: 'Santa casa de misericórdia de são Paulo',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'NATALIA AUGUSTO RODRIGUES BORTOLOTTI',
    cargo: 'Coordenadora da comissão permanente de Enfermagem Estética e Gestão de Negócios / Membro da Câmara Técnica de Legislação e Normas do Cofen',
    local_trabalho: 'COREN SP',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Bruna de Alencar Carvalho',
    cargo: 'Tec.de enfermagem',
    local_trabalho: 'Clínica nefrologica São Miguel',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Euzébia Xavier Ribeiro de Lima',
    cargo: 'TÉCNICO DE FARMÁCIA',
    local_trabalho: 'SPDM PAIS',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Cristiane Silva Salino',
    cargo: 'Assistente Social',
    local_trabalho: 'Associação Saúde da Família',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Maria Nilde Brito Dias',
    cargo: 'Enfermeira Assistencial',
    local_trabalho: 'AMA Parque Figueira Grande',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'BENEdito Alves de Souza',
    cargo: 'Conselheiro',
    local_trabalho: 'CMSSP',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Wilson Pereira de Souza junior',
    cargo: 'Técnico de Enfermagem',
    local_trabalho: 'INTS UPA SANTO AMARO',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'ELIANE DOS SANTOS DE SANTANA',
    cargo: 'ANALISTA DE GESTÃO DE PESSOAS PLENO',
    local_trabalho: 'SPDM AFILIADAS - FARMÁCIAS DE ALTO CUSTO',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Nicolau Marques dos Santos',
    cargo: 'Assistente de Farmácia',
    local_trabalho: 'Santa Casa de São Paulo',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Ana Paula putrino Tramonti',
    cargo: 'Técnico enfermagem',
    local_trabalho: 'Spdm',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Yago de Oliveira Torres Pinto',
    cargo: 'Médico de família e comunidade / médico plantonista UPA / Médico na saúde prisional / preceptor da residência Mfc Praia Grande - SP',
    local_trabalho: 'São Vicente SP ( vinculo via AGSUS ministério da saúde ) / Praia Grande - SP ( servidor público )',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Adenilza Alves de Souza',
    cargo: 'TEC de enfermagem',
    local_trabalho: 'Hospital da luz vila Mariana',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Elizete do Nascimento Silva',
    cargo: 'Técnico de enfermagem',
    local_trabalho: 'Hospital Alvorada de Moema',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Rosangela Batista Bergamo',
    cargo: 'Enfermeira Supervisora de Enfermagem',
    local_trabalho: 'Hospital da Mulher Seconci-SP',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Carolina Araújo Pontes',
    cargo: 'Auxiliar Administrativo',
    local_trabalho: 'Irmandade Santa Casa de Misericórdia de São Paulo',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Sinara da Silva Brito',
    cargo: 'Auxiliar de enfermagem/ Centro Cirúrgico',
    local_trabalho: 'Seconci',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'ELBA LUISA FORERO FIGUEIREDO',
    cargo: 'SUPERVISORA TÉCNICA - PROJETO REDE',
    local_trabalho: 'SPDM - ASSOCIAÇÃO PAULISTA PARA O DESENVOLVIMENTO DA MEDICINA',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Leda dos Santos Silva',
    cargo: 'Auxiliar Administrativo',
    local_trabalho: 'Santa casa/Hospital São Luiz Gonzaga',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Luiza da Cruz Caramelo',
    cargo: 'Supervisora técnica SADT',
    local_trabalho: 'SECONCI-SP/Hospital da Mulher',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Dyego Alves Gonçalves',
    cargo: 'Supervisor de Saúde',
    local_trabalho: 'Secretaria de Saúde de Mongaguá-SP',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Claudia Sales dos Santos',
    cargo: 'Supervisora de enfermagem',
    local_trabalho: 'SPDM',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Maria Agna Neres Barbosa',
    cargo: 'Técnica de enfermagem',
    local_trabalho: 'Ints',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Ronildo José dos Santos',
    cargo: 'Técnico de enfermagem',
    local_trabalho: 'Instituto Nacional de tecnologia e saúde INTS',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Abel Silva de Meneses',
    cargo: 'Gerente Técnico',
    local_trabalho: 'Centro de Estudos e Pesquisas Dr. João Amorim - CEJAM',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Roberto Enrique Kameo',
    cargo: 'Gerente Médico',
    local_trabalho: 'Hospital da Mulher - SECONCI SP',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Celso ricard Dell agnolo',
    cargo: 'Enfermeiro',
    local_trabalho: 'Hapvida',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Alexandre Yuri de Siqueira Souza',
    cargo: 'Auxiliar de enfermagem',
    local_trabalho: 'Disponível para o mercado de trabalho',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Maria não Carmo Ramos Viana',
    cargo: 'Enfermeira',
    local_trabalho: 'Ints',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Daniel Alves de Souza',
    cargo: 'Técnico de Enfermagem / Conselheiro',
    local_trabalho: 'Hospital do Servidor Público Estadual / Coren-SP',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Gladni Briz Hugolini',
    cargo: 'Coordenadora Assistencial',
    local_trabalho: 'Hospital Nove de Julho',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'BARBARA CANALE SPEZAMILIO',
    cargo: 'Auxiliar de enfermagem',
    local_trabalho: 'CAPS III SAPOPEMBA - SPDM',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Carlos Antônio dos Santos',
    cargo: 'Gerente de Enfermagem Corporativo',
    local_trabalho: 'Complexo de Saúde de São Bernardo do Campo',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Alexandre Neves de jesus',
    cargo: 'Agente de Promoção Ambiental',
    local_trabalho: 'Cejam',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Diane Carine Moura',
    cargo: 'Coordenadora de Administração de Pessoal',
    local_trabalho: 'Hospital Alemão Oswaldo Cruz',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Angélica Berenice Ramos dos Santos',
    cargo: 'Advogada',
    local_trabalho: 'ATML Associação Templo Morgana Luz',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Silvio César Gonçalves da Silva',
    cargo: 'Tecnico em enfermagem',
    local_trabalho: 'Hospital e Maternidade Cruz Azul',
    categoria: 'convidado',
    premiado: true,
  },
  {
    nome: 'Luciana Martins dos Santos',
    cargo: 'Coordenador de Adm Pessoal e Relações Trabalhistas e Sindicais',
    local_trabalho: 'Hospital Alemão Oswaldo Cruz',
    categoria: 'convidado',
    premiado: true,
  },

  // ── AUTORIDADES ─────────────────────────────────────────────────
  {
    nome: 'Adailton da Conceição Chiceri',
    categoria: 'autoridade',
  },
  {
    nome: 'Dr. Alexandre Cavalheiro',
    cargo: 'Médico',
    categoria: 'autoridade',
  },
  {
    nome: 'Bruna dos Anjos Rocha',
    cargo: 'Chefe de Gabinete',
    local_trabalho: 'Formada em Gestão Pública',
    categoria: 'autoridade',
  },
  {
    nome: 'Cláudio Santos',
    cargo: 'Jornalista, Ativista em Saúde, Acorrentado no Hosp. Brasilândia',
    categoria: 'autoridade',
  },
  {
    nome: 'Dr. Cleiton Sá',
    cargo: 'Perito Forense, Jornalista Investigador',
    categoria: 'autoridade',
  },
  {
    nome: 'Danielle Ferreira Nascimento Moraes',
    categoria: 'autoridade',
  },
  {
    nome: 'Francisco Teodoro Nobre',
    cargo: 'Cirurgião Cardiovascular',
    local_trabalho: 'Hospital Municipal Alexandre Zairo',
    categoria: 'autoridade',
  },
  {
    nome: 'Helena Souza Bezerra',
    categoria: 'autoridade',
  },
  {
    nome: 'Dr. Hercules Carlos',
    cargo: 'Médico',
    categoria: 'autoridade',
  },
  {
    nome: 'José Ricardo Coelho',
    categoria: 'autoridade',
  },
  {
    nome: 'Juliana dos Santos Barbalho',
    categoria: 'autoridade',
  },
  {
    nome: 'Miriam Costa',
    cargo: 'Advogada nos BR/USA, Jornalista',
    categoria: 'autoridade',
  },
  {
    nome: 'Paulo da Silva Amori',
    categoria: 'autoridade',
  },
  {
    nome: 'Paulo Tasso',
    categoria: 'autoridade',
  },
  {
    nome: 'Dr. Ramon Cavalcante',
    cargo: 'Médico',
    categoria: 'autoridade',
  },
  {
    nome: 'Vanessa Cavaco',
    cargo: 'Profissional da Saúde',
    categoria: 'autoridade',
  },

  // ── CONVIDADOS / HERÓIS DA SAÚDE ────────────────────────────────
  {
    nome: 'TIAGO CELESTINO CERQUEIRA',
    cargo: 'Geo das Organizações CINLEB',
    local_trabalho: 'Organizações Cinleb',
    categoria: 'convidado',
  },
  {
    nome: 'Alessandra Gonçalves de Oliveira',
    cargo: 'Advogada',
    local_trabalho: 'ALESP',
    categoria: 'convidado',
  },
  {
    nome: 'Mirelle Fabiana Trevisan',
    cargo: 'Técnica de Recursos Humanos',
    local_trabalho: '1ª Dama de Aracariguama',
    categoria: 'convidado',
  },
  {
    nome: 'Maria de Fátima Cavalcante Teixeira',
    cargo: 'Conselheira gestora de saúde São Paulo',
    local_trabalho: 'Hospital municipal Dr Alexandre Zaio',
    categoria: 'convidado',
  },
  {
    nome: 'Rômulo Benedito Cavalcante Teixeira',
    cargo: 'Medium',
    local_trabalho: 'Trabalhou 8 anos no AMA / UBS',
    categoria: 'convidado',
  },
  {
    nome: 'Dr. José de Lima Oliveira Junior',
    cargo: 'Médico - Cirurgião Cardiovascular Especialista em Transplantes de Coração',
    local_trabalho: 'InCor HC FMUSP',
    categoria: 'convidado',
  },
  {
    nome: 'Idinei Marcio Gomes',
    cargo: 'Fundador e Diretor Executivo',
    local_trabalho: 'L&I Consultoria Financeira e Intermediação de Negócios Ltda',
    categoria: 'convidado',
  },
  {
    nome: 'Maurício Andrade Rodrigues da Costa',
    cargo: 'Executivo de Gestão de Concessões e Infraestrutura Pública',
    local_trabalho: 'SP+Escolas',
    categoria: 'convidado',
  },

  // ── DIRETORES ───────────────────────────────────────────────────
  {
    nome: 'Alexandra Aparecida Muniz de Souza',
    local_trabalho: 'SINSAÚDE',
    categoria: 'diretor',
  },
  {
    nome: 'Ana Paula Ferreira',
    cargo: '1ª Secretária Geral',
    local_trabalho: 'SINSAÚDE',
    categoria: 'diretor',
  },
  {
    nome: 'André Luiz Pereira',
    local_trabalho: 'SINSAÚDE',
    categoria: 'diretor',
  },
  {
    nome: 'Azarias Viana da Silva',
    local_trabalho: 'SINSAÚDE',
    categoria: 'diretor',
  },
  {
    nome: 'Carlos Eduardo Oliveira da Silva',
    cargo: 'Diretor Social',
    local_trabalho: 'SINSAÚDE',
    categoria: 'diretor',
  },
  {
    nome: 'Cláudio Barnabé Cajado',
    cargo: 'Diretor de Esporte e Laser',
    local_trabalho: 'SINSAÚDE',
    categoria: 'diretor',
  },
  {
    nome: 'Cláudio Dermal Gonzales',
    local_trabalho: 'SINSAÚDE',
    categoria: 'diretor',
  },
  {
    nome: 'Edileuza Gomes Cardoso Amorim',
    local_trabalho: 'SINSAÚDE',
    categoria: 'diretor',
  },
  {
    nome: 'Edna Maria Marques',
    local_trabalho: 'SINSAÚDE',
    categoria: 'diretor',
  },
  {
    nome: 'Elane Clemente da Silva',
    local_trabalho: 'SINSAÚDE',
    categoria: 'diretor',
  },
  {
    nome: 'Eliane Tavares Gabriel',
    local_trabalho: 'SINSAÚDE',
    categoria: 'diretor',
  },
  {
    nome: 'Erivaldo José da Silva',
    cargo: 'Diretor de Cultura',
    local_trabalho: 'SINSAÚDE',
    categoria: 'diretor',
  },
  {
    nome: 'Eusébio Lucio da Rocha',
    cargo: 'Diretor Relações Públicas',
    local_trabalho: 'SINSAÚDE',
    categoria: 'diretor',
  },
  {
    nome: 'Filomena de Cassia Jerônimo',
    local_trabalho: 'SINSAÚDE',
    categoria: 'diretor',
  },
  {
    nome: 'Giovanna Tenguan',
    local_trabalho: 'SINSAÚDE',
    categoria: 'diretor',
  },
  {
    nome: 'Irenilda dos Santos',
    cargo: 'Secretária Geral',
    local_trabalho: 'SINSAÚDE',
    categoria: 'diretor',
  },
  {
    nome: 'Jefferson Erecy Santos Caproni',
    cargo: 'Presidente',
    local_trabalho: 'SINSAÚDE',
    categoria: 'diretor',
  },
  {
    nome: 'José Antônio dos Santos',
    cargo: '2º Tesoureiro',
    local_trabalho: 'SINSAÚDE',
    categoria: 'diretor',
  },
  {
    nome: 'Maria das Graças Oliveira Baima',
    local_trabalho: 'SINSAÚDE',
    categoria: 'diretor',
  },
  {
    nome: 'Maria José Cantanhede de Abreu',
    cargo: '1º Tesoureira',
    local_trabalho: 'SINSAÚDE',
    categoria: 'diretor',
  },
  {
    nome: 'Maria Luciene dos Santos',
    local_trabalho: 'SINSAÚDE',
    categoria: 'diretor',
  },
  {
    nome: 'Marucia da Conceição Adriana',
    local_trabalho: 'SINSAÚDE',
    categoria: 'diretor',
  },
  {
    nome: 'Oslei José Monteiro',
    local_trabalho: 'SINSAÚDE',
    categoria: 'diretor',
  },
  {
    nome: 'Paulo Sérgio de Oliveira',
    cargo: 'Diretor  Assuntos Jurídicos',
    local_trabalho: 'SINSAÚDE',
    categoria: 'diretor',
  },
  {
    nome: 'Reinaldo dos Santos Andrade',
    cargo: 'Vice- Presidente',
    local_trabalho: 'SINSAÚDE',
    categoria: 'diretor',
  },
  {
    nome: 'Rosana Gibello Gatto',
    cargo: '2 ª Vice-Presidente',
    local_trabalho: 'SINSAÚDE',
    categoria: 'diretor',
  },
  {
    nome: 'Rosangela Nunes de Souza',
    local_trabalho: 'SINSAÚDE',
    categoria: 'diretor',
  },
  {
    nome: 'Rumi Nagai',
    cargo: 'Tesoureira',
    local_trabalho: 'SINSAÚDE',
    categoria: 'diretor',
  },
  {
    nome: 'Sérgio Bezuglas Filho',
    cargo: '2º Secretário Geral',
    local_trabalho: 'SINSAÚDE',
    categoria: 'diretor',
  },
  {
    nome: 'Severino Alves de Siqueira',
    local_trabalho: 'SINSAÚDE',
    categoria: 'diretor',
  },
  {
    nome: 'Sonia Maria Camelo Campos da Cunha',
    local_trabalho: 'SINSAÚDE',
    categoria: 'diretor',
  },
  {
    nome: 'Vilson Bardela de Lima',
    cargo: 'Diretor de Patrimônio',
    local_trabalho: 'SINSAÚDE',
    categoria: 'diretor',
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// Execução
// ─────────────────────────────────────────────────────────────────────────────

const limpar = process.argv.includes('--limpar');

if (limpar) {
  db.exec(`DELETE FROM pessoas`);
  console.log('⚠  Cadastros anteriores removidos.\n');
}

const inserir = db.prepare(`
  INSERT INTO pessoas (nome, cargo, local_trabalho, categoria, status, premiado, na_lista_original)
  VALUES (?, ?, ?, ?, 'pendente', ?, 1)
`);

const existe = db.prepare(`SELECT id FROM pessoas WHERE LOWER(TRIM(nome)) = LOWER(TRIM(?))`);

let inseridos = 0, ignorados = 0;

for (const p of PESSOAS) {
  const nome = (p.nome || '').trim();
  if (!nome) continue;
  if (!limpar && existe.get(nome)) {
    console.log('  → já existe:', nome);
    ignorados++;
    continue;
  }
  inserir.run(nome, p.cargo || '', p.local_trabalho || '', p.categoria || 'convidado', p.premiado ? 1 : 0);
  console.log('  ✔', p.categoria.padEnd(10), nome);
  inseridos++;
}

console.log('\nConcluído:', inseridos, 'inserido(s),', ignorados, 'ignorado(s).');
